# Generated by Django 5.0.1 on 2024-01-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='category',
        ),
        migrations.RemoveField(
            model_name='abc',
            name='image',
        ),
        migrations.AddField(
            model_name='abc',
            name='amenities',
            field=models.CharField(default='default_value_here', max_length=255),
        ),
    ]
