# Generated by Django 5.0.1 on 2024-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_remove_abc_category_remove_abc_image_abc_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
