# Generated by Django 5.0.1 on 2024-01-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0004_alter_abc_amenities_alter_abc_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abc',
            old_name='amenities',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='abc',
            name='details',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='abc',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
